<h3>Pandas is a powerful python library desinged for data manipulation (cleaning, transforming, structuring data) and data analysis (finding pattern, trends, insights).
It simplifies working with structured datasets like tables, spreadsheets, or time-series-data.<h3>

In [5]:
import pandas as pd

<h3>Saving and read the data</h3>

Read the data from file .csv, .xlsx, .json

In [7]:
import pandas as pd
df_csv = pd.read_csv(r'../sample_data/sample_data.csv', encoding='utf-8')
# encoding = utf-8 tell pandas translate the raw 0 and 1, in the file into actual letters you can read.

df_xlsx = pd.read_excel(r'../sample_data/sample_data.xlsx')
df_json = pd.read_json(r'../sample_data/sample_data.json')

print('CSV')
print(df_csv)

print('Excel')
print(df_xlsx)

print('Json')
print(df_json)

CSV
   ID     Name   Department  Salary
0   1    Alice        Sales   55000
1   2      Bob  Engineering   72000
2   3  Charlie           HR   48000
Excel
   ID     Name   Department  Salary
0   1    Alice        Sales   55000
1   2      Bob  Engineering   72000
2   3  Charlie           HR   48000
Json
    id                                               name  \
0    1                                    Apple iPhone 12
1    2                                 Samsung Galaxy S21
2    3                                 Sony PlayStation 5
3    4                  LG OLED55CXPUA 55-inch 4K OLED TV
4    5        Bose QuietComfort 35 II Wireless Headphones
5    6                          Fitbit Versa 3 Smartwatch
6    7                             KitchenAid Stand Mixer
7    8                 Dyson V11 Absolute Cordless Vacuum
8    9                         Ninja Foodi Smart XL Grill
9   10                    Canon EOS Rebel T8i DSLR Camera
10  11                                  Apple AirPods Pro
11  12        Bose QuietComfort 35 II Wireless Headphones
12  13                    Fitbit Charge 4 Fitness Tracker
13  14                              Samsung Galaxy Watch3
14  15  Sony WH-1000XM4 Wireless Noise-Cancelling Head...
15  16          Breville Barista Express Espresso Machine
16  17                        Keurig K-Elite Coffee Maker
17  18                     iRobot Roomba i7+ Robot Vacuum
18  19                   Ninja Foodi Digital Air Fry Oven
19  20                   Cuisinart ICE-70 Ice Cream Maker

                                          description    price  \
0   The Apple iPhone 12 features a 6.1-inch Super ...   999.00
1   The Samsung Galaxy S21 features a 6.2-inch Dyn...   799.00
2   The Sony PlayStation 5 features an AMD Zen 2-b...   499.99
3   The LG OLED55CXPUA 55-inch 4K OLED TV features...  1599.99
4   The Bose QuietComfort 35 II Wireless Headphone...   299.00
5   The Fitbit Versa 3 Smartwatch features a built...   229.95
6   The KitchenAid Stand Mixer features a 5-quart ...   399.99
7   The Dyson V11 Absolute Cordless Vacuum feature...   699.99
8   The Ninja Foodi Smart XL Grill features 6-in-1...   279.99
9   The Canon EOS Rebel T8i DSLR Camera features a...   899.00
10  The Apple AirPods Pro feature active noise can...   249.00
11  The Bose QuietComfort 35 II Wireless Headphone...   299.00
12  The Fitbit Charge 4 Fitness Tracker features G...   129.95
13  The Samsung Galaxy Watch3 features a rotating ...   399.99
14  The Sony WH-1000XM4 Wireless Noise-Cancelling ...   349.99
15  The Breville Barista Express Espresso Machine ...   699.95
16  The Keurig K-Elite Coffee Maker features a str...   169.99
17  The iRobot Roomba i7+ Robot Vacuum features au...   799.99
18  The Ninja Foodi Digital Air Fry Oven features ...   209.99
19  The Cuisinart ICE-70 Ice Cream Maker features ...   139.99

           category                                              image
0       Electronics  https://www.apple.com/newsroom/images/product/...
1       Electronics  https://images.samsung.com/is/image/samsung/p6...
2       Electronics  https://www.sony.com/image/44baa604124b770c824...
3       Electronics  https://www.lg.com/us/images/tvs/md07501804/ga...
4       Electronics  https://assets.bose.com/content/dam/Bose_DAM/W...
5       Electronics  https://www.fitbit.com/global/content/dam/fitb...
6    Home & Kitchen  https://www.kitchenaid.com/content/dam/global/...
7   Home Appliances  https://www.dysoncanada.ca/dam/dyson/images/pr...
8    Home & Kitchen  https://www.ninjakitchen.com/medias/Ninja-OP50...
9       Electronics  https://www.canon.com.au/-/media/images/produc...
10      Electronics  https://www.apple.com/v/airpods-pro/b/images/m...
11      Electronics  https://assets.bose.com/content/dam/Bose_DAM/W...
12      Electronics  https://www.fitbit.com/global/content/dam/fitb...
13      Electronics  https://images.samsung.com/is/image/samsung/as...
14      Electronics  https://www.sony.com/image/1cdd6354c4cd21cc4f7...
15   Home & Kitchen  https://www.breville.com/content/dam/breville/...
16   Home & Kitchen  https://www.keurig.com/content/dam/global-ecom...
17   Home & Kitchen  https://store.irobot.com/default/i7-vacuuming-...
18   Home & Kitchen  https://www.ninjakitchen.com/static/img/produc...
19   Home & Kitchen  https://www.cuisinart.com/share/images/product...

gcsfs is a Python library that allows you to read and write files stored in Google Cloud Storage (GCS)

In [8]:
'''How to save the data in file (csv,xlsx, json etc.) after cleaning , manipulation of data. Let see'''
import pandas as pd

data = {
    'Name': ['John', 'Bob', 'Dal'],
    'Age' : [10, 20, 30],
    'City' : ['Newyork', 'Chicago', 'New Jersy']
}

df = pd.DataFrame(data)
df
df.to_csv(r"output.csv", index=False)
df.to_excel(r"output.xlsx", index=False)
df.to_json(r"output.json", index=False)

In [ ]:
df

   Name  Age       City
0  John   10    Newyork
1   Bob   20    Chicago
2   Dal   30  New Jersy

In [9]:
#reading the save file.

import pandas as pd

df = pd.read_csv(r'output.csv')
print(df.to_string(index=False))

Name  Age      City
John   10   Newyork
 Bob   20   Chicago
 Dal   30 New Jersy

Read the data,
Understand the data,
Identify the data

In [ ]:
'''check the first and last rows of data unsing pd.head() and pd.tail()'''

'check the first and last rows of data unsing pd.head() and pd.tail()'

In [10]:
import pandas as pd
df = pd.read_json('../sample_Data/sample_Data.json')
df.head()

,id,name,description,price,category,image
0,1,Apple iPhone 12,The Apple iPhone 12 features a 6.1-inch Super ...,999.00,Electronics,https://www.apple.com/newsroom/images/product/...
1,2,Samsung Galaxy S21,The Samsung Galaxy S21 features a 6.2-inch Dyn...,799.00,Electronics,https://images.samsung.com/is/image/samsung/p6...
2,3,Sony PlayStation 5,The Sony PlayStation 5 features an AMD Zen 2-b...,499.99,Electronics,https://www.sony.com/image/44baa604124b770c824...
3,4,LG OLED55CXPUA 55-inch 4K OLED TV,The LG OLED55CXPUA 55-inch 4K OLED TV features...,1599.99,Electronics,https://www.lg.com/us/images/tvs/md07501804/ga...
4,5,Bose QuietComfort 35 II Wireless Headphones,The Bose QuietComfort 35 II Wireless Headphone...,299.00,Electronics,https://assets.bose.com/content/dam/Bose_DAM/W...

In [11]:
import pandas as pd
df = pd.read_json('../sample_Data/sample_Data.json')
df.tail()

,id,name,description,price,category,image
15,16,Breville Barista Express Espresso Machine,The Breville Barista Express Espresso Machine ...,699.95,Home & Kitchen,https://www.breville.com/content/dam/breville/...
16,17,Keurig K-Elite Coffee Maker,The Keurig K-Elite Coffee Maker features a str...,169.99,Home & Kitchen,https://www.keurig.com/content/dam/global-ecom...
17,18,iRobot Roomba i7+ Robot Vacuum,The iRobot Roomba i7+ Robot Vacuum features au...,799.99,Home & Kitchen,https://store.irobot.com/default/i7-vacuuming-...
18,19,Ninja Foodi Digital Air Fry Oven,The Ninja Foodi Digital Air Fry Oven features ...,209.99,Home & Kitchen,https://www.ninjakitchen.com/static/img/produc...
19,20,Cuisinart ICE-70 Ice Cream Maker,The Cuisinart ICE-70 Ice Cream Maker features ...,139.99,Home & Kitchen,https://www.cuisinart.com/share/images/product...

In [ ]:
'''why do we need to read and understand the data?
Because we dont know about that
1- How many rows and columns in dataset.
2- How many null counts, missing values in each column.
3- what is the data type of each column.
'''

'why do we need to read and understand the data?\nBecause we dont know about that\n1- How many rows and columns in dataset.\n2- How many null counts, missing values in each column.\n3- what is the data type of each column.\n'

In [12]:
'''pd.info() give the summary data espcially use for this'''
import pandas as pd
df = pd.read_json('../sample_Data/sample_Data.json')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           20 non-null     int64
 1   name         20 non-null     str
 2   description  20 non-null     str
 3   price        20 non-null     float64
 4   category     20 non-null     str
 5   image        20 non-null     str
dtypes: float64(1), int64(1), str(4)
memory usage: 6.2 KB

In [13]:
'''
df.describe() 
give the descriptive statistical summary about each of data
'''

'\ndf.describe() \ngive the descriptive statistical summary about each of data\n'

In [14]:
data = {
    "Name": ["Ali", "Sara", "John", "Ayesha", "David",
             "Hamza", "Emma", "Usman", "Sophia", "Bilal"],

    "Age": [22, 25, 28, 21, 30, 24, 27, 23, 29, 26],

    "Gender": ["Male", "Female", "Male", "Female", "Male",
               "Male", "Female", "Male", "Female", "Male"],

    "City": ["Lahore", "Karachi", "Islamabad", "Lahore", "Multan",
             "Karachi", "Lahore", "Islamabad", "Multan", "Karachi"],

    "Salary": [45000, 55000, 70000, 40000, 85000,
               50000, 65000, 48000, 75000, 60000],

    "Department": ["IT", "HR", "Finance", "IT", "Marketing",
                   "Finance", "HR", "IT", "Marketing", "Finance"],

    "Experience": [1, 3, 5, 1, 7, 2, 4, 2, 6, 3]
}

df = pd.DataFrame(data)
print(df)

df.describe()

     Name  Age  Gender       City  Salary Department  Experience
0     Ali   22    Male     Lahore   45000         IT           1
1    Sara   25  Female    Karachi   55000         HR           3
2    John   28    Male  Islamabad   70000    Finance           5
3  Ayesha   21  Female     Lahore   40000         IT           1
4   David   30    Male     Multan   85000  Marketing           7
5   Hamza   24    Male    Karachi   50000    Finance           2
6    Emma   27  Female     Lahore   65000         HR           4
7   Usman   23    Male  Islamabad   48000         IT           2
8  Sophia   29  Female     Multan   75000  Marketing           6
9   Bilal   26    Male    Karachi   60000    Finance           3

            Age        Salary  Experience
count  10.00000     10.000000   10.000000
mean   25.50000  59300.000000    3.400000
std     3.02765  14391.741459    2.065591
min    21.00000  40000.000000    1.000000
25%    23.25000  48500.000000    2.000000
50%    25.50000  57500.000000    3.000000
75%    27.75000  68750.000000    4.750000
max    30.00000  85000.000000    7.000000

In [ ]:
'''How to check the quickly (rows, columns) in data and name of columns
use the df.shape() , df.columns()
'''

In [15]:
import pandas as pd

data = {
    "Name": ["Ali", "Sara", "John", "Ayesha", "David",
                 "Hamza", "Emma", "Usman", "Sophia", "Bilal"],
    
    "Age": [22, 25, 28, 21, 30, 24, 27, 23, 29, 26],
    
    "Gender": ["Male", "Female", "Male", "Female", "Male",
                   "Male", "Female", "Male", "Female", "Male"],
    
    "City": ["Lahore", "Karachi", "Islamabad", "Lahore", "Multan",
                 "Karachi", "Lahore", "Islamabad", "Multan", "Karachi"],
    
    "Salary": [45000, 55000, 70000, 40000, 85000,
                   50000, 65000, 48000, 75000, 60000],
    
    "Department": ["IT", "HR", "Finance", "IT", "Marketing",
                       "Finance", "HR", "IT", "Marketing", "Finance"],
    
    "Experience": [1, 3, 5, 1, 7, 2, 4, 2, 6, 3]
}

print(f'Shape : {df.shape}')
print(f'Columns : {df.columns}')

Shape : (10, 7)
Columns : Index(['Name', 'Age', 'Gender', 'City', 'Salary', 'Department', 'Experience'], dtype='str')

In [ ]:
'''
let's understand the syntax and how columns are selected , filtering rows -> base on single boolean condition, 
and mutiple boolean condition etc. in numpy pandas.
'''

"\nlet's understand the syntax and how columns are selected , filtering rows -> base on single boolean condition, \nand mutiple boolean condition etc. in numpy pandas.\n"

In [16]:
# Data frame
import pandas as pd

data = {
    "Name": ["Ali", "Sara", "John", "Ayesha", "David",
                 "Hamza", "Emma", "Usman", "Sophia", "Bilal"],
    
    "Age": [22, 25, 28, 21, 30, 24, 27, 23, 29, 26],
    
    "Gender": ["Male", "Female", "Male", "Female", "Male",
                   "Male", "Female", "Male", "Female", "Male"],
    
    "City": ["Lahore", "Karachi", "Islamabad", "Lahore", "Multan",
                 "Karachi", "Lahore", "Islamabad", "Multan", "Karachi"],
    
    "Salary": [45000, 55000, 70000, 40000, 85000,
                   50000, 65000, 48000, 75000, 60000],
    
    "Department": ["IT", "HR", "Finance", "IT", "Marketing",
                       "Finance", "HR", "IT", "Marketing", "Finance"],
    
    "Experience": [1, 3, 5, 1, 7, 2, 4, 2, 6, 3]
}

df = pd.DataFrame(data)

In [17]:
#select the single column
name = df['Name']
name

0       Ali
1      Sara
2      John
3    Ayesha
4     David
5     Hamza
6      Emma
7     Usman
8    Sophia
9     Bilal
Name: Name, dtype: str

In [18]:
# selecting the multiple columns by passing the list into dataframe like df[['col1','col2','col3']] (subset)
subset = df[['Name', 'Age', 'Salary']]
subset

     Name  Age  Salary
0     Ali   22   45000
1    Sara   25   55000
2    John   28   70000
3  Ayesha   21   40000
4   David   30   85000
5   Hamza   24   50000
6    Emma   27   65000
7   Usman   23   48000
8  Sophia   29   75000
9   Bilal   26   60000

In [19]:
# implemtenting the boolean condition on single and multiple columns.
import pandas as pd

data = {
    "Name": ["Ali", "Sara", "John", "Ayesha", "David",
                 "Hamza", "Emma", "Usman", "Sophia", "Bilal"],
    
    "Age": [22, 25, 28, 21, 30, 24, 27, 23, 29, 26],
    
    "Gender": ["Male", "Female", "Male", "Female", "Male",
                   "Male", "Female", "Male", "Female", "Male"],
    
    "City": ["Lahore", "Karachi", "Islamabad", "Lahore", "Multan",
                 "Karachi", "Lahore", "Islamabad", "Multan", "Karachi"],
    
    "Salary": [45000, 55000, 70000, 40000, 85000,
                   50000, 65000, 48000, 75000, 60000],
    
    "Department": ["IT", "HR", "Finance", "IT", "Marketing",
                       "Finance", "HR", "IT", "Marketing", "Finance"],
    
    "Experience": [1, 3, 5, 1, 7, 2, 4, 2, 6, 3],

    "PerformanceScore" : [40,45,50,55,60,65,70,80,85,90]
}

df = pd.DataFrame(data)

In [20]:
"""filter those employees data their salary is greater than 50,000"""
data = df[df['Salary'] >= 50000]
data

,Name,Age,Gender,City,Salary,Department,Experience,PerformanceScore
1,Sara,25,Female,Karachi,55000,HR,3,45
2,John,28,Male,Islamabad,70000,Finance,5,50
4,David,30,Male,Multan,85000,Marketing,7,60
5,Hamza,24,Male,Karachi,50000,Finance,2,65
6,Emma,27,Female,Lahore,65000,HR,4,70
8,Sophia,29,Female,Multan,75000,Marketing,6,85
9,Bilal,26,Male,Karachi,60000,Finance,3,90

In [21]:
'''filter those employees data their salary is greater than or equal to 50,000 
and age is greater than or equal to 30'''
data = df[(df['Salary'] >=50000) & (df['Age']>=30)]
data

    Name  Age Gender    City  Salary Department  Experience  PerformanceScore
4  David   30   Male  Multan   85000  Marketing           7                60

In [22]:
'''
Using OR condition
filter such employess their salary is greater than 50,000 or Performance score is also greater than 50
'''
data = df[(df['Salary'] >= 50000) | (df['PerformanceScore'] >= 50)]
data

,Name,Age,Gender,City,Salary,Department,Experience,PerformanceScore
1,Sara,25,Female,Karachi,55000,HR,3,45
2,John,28,Male,Islamabad,70000,Finance,5,50
3,Ayesha,21,Female,Lahore,40000,IT,1,55
4,David,30,Male,Multan,85000,Marketing,7,60
5,Hamza,24,Male,Karachi,50000,Finance,2,65
6,Emma,27,Female,Lahore,65000,HR,4,70
7,Usman,23,Male,Islamabad,48000,IT,2,80
8,Sophia,29,Female,Multan,75000,Marketing,6,85
9,Bilal,26,Male,Karachi,60000,Finance,3,90

<h1>Advanced Pandas</h1>

In [23]:
import pandas as pd
data = {
    "Name": [
        "Alice Smith",
        "Bob Jones",
        "Charlie Brown",
        "Diana Prince",
        "Evan Wright",
        "Fiona Gallagher",
        "George Clark",
        "Hannah Abbott",
        "Ian Malcolm",
        "Julia Roberts"
    ],
    "Age": [28, 34, 25, 41, 29, 32, 45, 23, 38, 50],
    "Salary": [65000, 82000, 54000, 95000, 68000, 72000, 110000, 48000, 87000, 125000],
    "PerformanceScore": [4.2, 3.8, 4.5, 4.9, 3.5, 4.0, 4.7, 3.9, 4.1, 4.8]
}

df = pd.DataFrame(data)
df

              Name  Age  Salary  PerformanceScore
0      Alice Smith   28   65000               4.2
1        Bob Jones   34   82000               3.8
2    Charlie Brown   25   54000               4.5
3     Diana Prince   41   95000               4.9
4      Evan Wright   29   68000               3.5
5  Fiona Gallagher   32   72000               4.0
6     George Clark   45  110000               4.7
7    Hannah Abbott   23   48000               3.9
8      Ian Malcolm   38   87000               4.1
9    Julia Roberts   50  125000               4.8

<h3> Add Column in existing frame</h3>

In [24]:
'''add the column in existing pandas DataFrame using insert method
df.insert(loc, col_name, data)
- loc means index location of column to insert
'''
import numpy as np
df.insert(0, "EmployeeID", np.arange(101, 111))
df

   EmployeeID             Name  Age  Salary  PerformanceScore
0         101      Alice Smith   28   65000               4.2
1         102        Bob Jones   34   82000               3.8
2         103    Charlie Brown   25   54000               4.5
3         104     Diana Prince   41   95000               4.9
4         105      Evan Wright   29   68000               3.5
5         106  Fiona Gallagher   32   72000               4.0
6         107     George Clark   45  110000               4.7
7         108    Hannah Abbott   23   48000               3.9
8         109      Ian Malcolm   38   87000               4.1
9         110    Julia Roberts   50  125000               4.8

In [25]:
'''after that in this frame also i want to add the column 'Bonus Column' = 10% of salary'''
df.insert(5, "Bonus", df['Salary']*0.1)
df

   EmployeeID             Name  Age  Salary  PerformanceScore    Bonus
0         101      Alice Smith   28   65000               4.2   6500.0
1         102        Bob Jones   34   82000               3.8   8200.0
2         103    Charlie Brown   25   54000               4.5   5400.0
3         104     Diana Prince   41   95000               4.9   9500.0
4         105      Evan Wright   29   68000               3.5   6800.0
5         106  Fiona Gallagher   32   72000               4.0   7200.0
6         107     George Clark   45  110000               4.7  11000.0
7         108    Hannah Abbott   23   48000               3.9   4800.0
8         109      Ian Malcolm   38   87000               4.1   8700.0
9         110    Julia Roberts   50  125000               4.8  12500.0

<h3> Update column in data frame </h3>

In [26]:
import pandas as pd
data = {
    "Name": [
        "Alice Smith",
        "Bob Jones",
        "Charlie Brown",
        "Diana Prince",
        "Evan Wright",
        "Fiona Gallagher",
        "George Clark",
        "Hannah Abbott",
        "Ian Malcolm",
        "Julia Roberts"
    ],
    "Age": [28, 34, 25, 41, 29, 32, 45, 23, 38, 50],
    "Salary": [65000, 82000, 54000, 95000, 68000, 72000, 110000, 48000, 87000, 125000],
    "PerformanceScore": [4.2, 3.8, 4.5, 4.9, 3.5, 4.0, 4.7, 3.9, 4.1, 4.8]
}

df = pd.DataFrame(data)
df

              Name  Age  Salary  PerformanceScore
0      Alice Smith   28   65000               4.2
1        Bob Jones   34   82000               3.8
2    Charlie Brown   25   54000               4.5
3     Diana Prince   41   95000               4.9
4      Evan Wright   29   68000               3.5
5  Fiona Gallagher   32   72000               4.0
6     George Clark   45  110000               4.7
7    Hannah Abbott   23   48000               3.9
8      Ian Malcolm   38   87000               4.1
9    Julia Roberts   50  125000               4.8

.loc[ ]

In [27]:
'''update the specific cell in the data by using:
df.loc[row_index, col_name] = data

update the salary of the Alice Smith
'''
df.loc[0, 'Salary'] = 70000
df

              Name  Age  Salary  PerformanceScore
0      Alice Smith   28   70000               4.2
1        Bob Jones   34   82000               3.8
2    Charlie Brown   25   54000               4.5
3     Diana Prince   41   95000               4.9
4      Evan Wright   29   68000               3.5
5  Fiona Gallagher   32   72000               4.0
6     George Clark   45  110000               4.7
7    Hannah Abbott   23   48000               3.9
8      Ian Malcolm   38   87000               4.1
9    Julia Roberts   50  125000               4.8

In [28]:
# Increase the salary of every employee by 5%.
df['Salary'] = df['Salary'] * 1.05
df

              Name  Age    Salary  PerformanceScore
0      Alice Smith   28   73500.0               4.2
1        Bob Jones   34   86100.0               3.8
2    Charlie Brown   25   56700.0               4.5
3     Diana Prince   41   99750.0               4.9
4      Evan Wright   29   71400.0               3.5
5  Fiona Gallagher   32   75600.0               4.0
6     George Clark   45  115500.0               4.7
7    Hannah Abbott   23   50400.0               3.9
8      Ian Malcolm   38   91350.0               4.1
9    Julia Roberts   50  131250.0               4.8

<h3> Remove the columns or column form Data Frame</h3>

In [29]:
'''
df.drop(columns=[Column1, Column2], inplace=True)
inplace=True means in this change happen in the original DataFrame, not a new one data Fram is returned.
'''

'\ndf.drop(columns=[Column1, Column2], inplace=True)\ninplace=True means in this change happen in the original DataFrame, not a new one data Fram is returned.\n'

In [38]:
import pandas as pd
data = {
    "Name": [
        "Alice Smith",
        "Bob Jones",
        "Charlie Brown",
        "Diana Prince",
        "Evan Wright",
        "Fiona Gallagher",
        "George Clark",
        "Hannah Abbott",
        "Ian Malcolm",
        "Julia Roberts"
    ],
    "Age": [28, 34, 25, 41, 29, 32, 45, 23, 38, 50],
    "Salary": [65000, 82000, 54000, 95000, 68000, 72000, 110000, 48000, 87000, 125000],
    "PerformanceScore": [4.2, 3.8, 4.5, 4.9, 3.5, 4.0, 4.7, 3.9, 4.1, 4.8]
}

df = pd.DataFrame(data)
df

              Name  Age  Salary  PerformanceScore
0      Alice Smith   28   65000               4.2
1        Bob Jones   34   82000               3.8
2    Charlie Brown   25   54000               4.5
3     Diana Prince   41   95000               4.9
4      Evan Wright   29   68000               3.5
5  Fiona Gallagher   32   72000               4.0
6     George Clark   45  110000               4.7
7    Hannah Abbott   23   48000               3.9
8      Ian Malcolm   38   87000               4.1
9    Julia Roberts   50  125000               4.8

In [39]:
'''Remove the Column Performance Score from this Data Frame'''
df.drop(columns=['PerformanceScore', 'Age'], inplace=True)
print('After Drop or Removing the Age and PerformanceScore')
df

After Drop or Removing the Age and PerformanceScore

              Name  Salary
0      Alice Smith   65000
1        Bob Jones   82000
2    Charlie Brown   54000
3     Diana Prince   95000
4      Evan Wright   68000
5  Fiona Gallagher   72000
6     George Clark  110000
7    Hannah Abbott   48000
8      Ian Malcolm   87000
9    Julia Roberts  125000