<h1>Handling Missing Values Using Pandas</h1>

<h3>Detecting a missing value in Data Frame</h3>

In [1]:
'''
np.isnull()
return 
TRUE for missing values, 
FALSE for non-missing values means value is actually present.

Missing value can be in the column or data:
1- NaN 
2- None
'''

'\nnp.isnull()\nreturn \nTRUE for missing values, \nFALSE for non-missing values means value is actually present.\n\nMissing value can be in the column or data:\n1- NaN \n2- None\n'

In [2]:
import pandas as pd
data = {
    "Name": [
        "Alice Smith",
        None,
        "Charlie Brown",
        "Diana Prince",
        "Evan Wright",
        "Fiona Gallagher",
        "George Clark",
        "Hannah Abbott",
        "Ian Malcolm",
        "Julia Roberts"
    ],
    "Age": [28, None, 25, 41, 29, 32, 45, 23, 38, 50],
    "Salary": [65000, None, 54000, 95000, 68000, 72000, 110000, 48000, 87000, 125000],
    "PerformanceScore": [4.2, None, 4.5, 4.9, 3.5, 4.0, 4.7, 3.9, 4.1, 4.8]
}

df = pd.DataFrame(data)
df

              Name   Age    Salary  PerformanceScore
0      Alice Smith  28.0   65000.0               4.2
1              NaN   NaN       NaN               NaN
2    Charlie Brown  25.0   54000.0               4.5
3     Diana Prince  41.0   95000.0               4.9
4      Evan Wright  29.0   68000.0               3.5
5  Fiona Gallagher  32.0   72000.0               4.0
6     George Clark  45.0  110000.0               4.7
7    Hannah Abbott  23.0   48000.0               3.9
8      Ian Malcolm  38.0   87000.0               4.1
9    Julia Roberts  50.0  125000.0               4.8

In [4]:
print(df.isnull())
print(df.isnull().sum())

    Name    Age  Salary  PerformanceScore
0  False  False   False             False
1   True   True    True              True
2  False  False   False             False
3  False  False   False             False
4  False  False   False             False
5  False  False   False             False
6  False  False   False             False
7  False  False   False             False
8  False  False   False             False
9  False  False   False             False
Name                1
Age                 1
Salary              1
PerformanceScore    1
dtype: int64

<h3>Drop the row or column that contains the missing value</h3>

In [11]:
'''
use df.dropna(axis=0 Or 1, inplace=True Or False)
'''
import pandas as pd
data = {
    "Name": [
        "Alice Smith",
        None,
        "Charlie Brown",
        "Diana Prince",
        "Evan Wright",
        "Fiona Gallagher",
        "George Clark",
        "Hannah Abbott",
        "Ian Malcolm",
        "Julia Roberts"
    ],
    "Age": [28, None, 25, 41, 29, 32, 45, 23, 38, 50],
    "Salary": [65000, None, 54000, 95000, 68000, 72000, 110000, 48000, 87000, 125000],
    "PerformanceScore": [4.2, None, 4.5, 4.9, 3.5, 4.0, 4.7, 3.9, 4.1, 4.8]
}

df = pd.DataFrame(data)
df

              Name   Age    Salary  PerformanceScore
0      Alice Smith  28.0   65000.0               4.2
1              NaN   NaN       NaN               NaN
2    Charlie Brown  25.0   54000.0               4.5
3     Diana Prince  41.0   95000.0               4.9
4      Evan Wright  29.0   68000.0               3.5
5  Fiona Gallagher  32.0   72000.0               4.0
6     George Clark  45.0  110000.0               4.7
7    Hannah Abbott  23.0   48000.0               3.9
8      Ian Malcolm  38.0   87000.0               4.1
9    Julia Roberts  50.0  125000.0               4.8

In [12]:
df.dropna(axis=0, inplace=True)
df

              Name   Age    Salary  PerformanceScore
0      Alice Smith  28.0   65000.0               4.2
2    Charlie Brown  25.0   54000.0               4.5
3     Diana Prince  41.0   95000.0               4.9
4      Evan Wright  29.0   68000.0               3.5
5  Fiona Gallagher  32.0   72000.0               4.0
6     George Clark  45.0  110000.0               4.7
7    Hannah Abbott  23.0   48000.0               3.9
8      Ian Malcolm  38.0   87000.0               4.1
9    Julia Roberts  50.0  125000.0               4.8

In [ ]:
'''If the missing values are frequent in data then it is not good practice to drop the rows, 
this can cause the data loss
so, replace these missing values with some default values, or calculated values. A good approach.
'''

'If the missing values are frequent in data then it is not good practice to drop the rows, \ncan cause the data loss\nso, replace these missing values with some default values, or calculated values. A good approach.\n'

Replace the missing values instead of droping them

In [39]:
'''df.fillna(value, inplace) used to replace the missing value with calculated or default value'''
'''
use df.dropna(axis=0 Or 1, inplace=True Or False)
'''
import pandas as pd
data = {
    "Name": [
        "Alice Smith",
        None,
        "Charlie Brown",
        "Diana Prince",
        "Evan Wright",
        "Fiona Gallagher",
        "George Clark",
        "Hannah Abbott",
        "Ian Malcolm",
        "Julia Roberts"
    ],
    "Age": [28, None, 25, 41, 29, 32, 45, 23, 38, 50],
    "Salary": [65000, None, 54000, 95000, 68000, 72000, 110000, 48000, 87000, 125000],
    "PerformanceScore": [4.2, None, 4.5, 4.9, 3.5, 4.0, 4.7, 3.9, 4.1, 4.8]
}

df = pd.DataFrame(data)
df

              Name   Age    Salary  PerformanceScore
0      Alice Smith  28.0   65000.0               4.2
1              NaN   NaN       NaN               NaN
2    Charlie Brown  25.0   54000.0               4.5
3     Diana Prince  41.0   95000.0               4.9
4      Evan Wright  29.0   68000.0               3.5
5  Fiona Gallagher  32.0   72000.0               4.0
6     George Clark  45.0  110000.0               4.7
7    Hannah Abbott  23.0   48000.0               3.9
8      Ian Malcolm  38.0   87000.0               4.1
9    Julia Roberts  50.0  125000.0               4.8

In [40]:
df['Name'] = df['Name'].fillna('Unknown')
df['Age'] = df['Age'].fillna(df['Age'].mean())
df['Salary'] = df['Salary'].fillna(df['Salary'].mean())
df['PerformanceScore'] = df['PerformanceScore'].fillna(0)
df

              Name        Age         Salary  PerformanceScore
0      Alice Smith  28.000000   65000.000000               4.2
1          Unknown  34.555556   80444.444444               0.0
2    Charlie Brown  25.000000   54000.000000               4.5
3     Diana Prince  41.000000   95000.000000               4.9
4      Evan Wright  29.000000   68000.000000               3.5
5  Fiona Gallagher  32.000000   72000.000000               4.0
6     George Clark  45.000000  110000.000000               4.7
7    Hannah Abbott  23.000000   48000.000000               3.9
8      Ian Malcolm  38.000000   87000.000000               4.1
9    Julia Roberts  50.000000  125000.000000               4.8

In [41]:
df['Age'] = df['Age'].astype(int)
df['Salary'] = df['Salary'].round(2)
df

              Name  Age     Salary  PerformanceScore
0      Alice Smith   28   65000.00               4.2
1          Unknown   34   80444.44               0.0
2    Charlie Brown   25   54000.00               4.5
3     Diana Prince   41   95000.00               4.9
4      Evan Wright   29   68000.00               3.5
5  Fiona Gallagher   32   72000.00               4.0
6     George Clark   45  110000.00               4.7
7    Hannah Abbott   23   48000.00               3.9
8      Ian Malcolm   38   87000.00               4.1
9    Julia Roberts   50  125000.00               4.8

<h3>Interpolation</h3>

In [ ]:
'''Interpolation is a way of estimating a missing value by looking at the values around it.
1- Linear Interpolation (estime missing value by looking before and after values).
2- Polynomial Interpolation (use when data grows very fast or increasingly with  and non linear relation, and curved data.)
3- Time Interpolation (estime a missing value base on time closest intervals between the observation)
'''

'Interpolation is a way of estimating a missing value by looking at the values around it.\n1- Linear Interpolation (estime missing value by looking before and after values).\n2- Polynomial Interpolation (use when data grows very fast or increasingly and non linear relation, and curved data.)\n3- Time Interpolation (estime a missing value base on time closest intervals between the observation)\n'

In [65]:
'''Linear Interpolation'''
import pandas as pd
data = {
    'Time' : [1, 2, 3, 4, 5],
    'Speed' : [10, 20, None, 40, 50]
}

df = pd.DataFrame(data)
print('Data with missing Values')
print(df)

print('\nApply the Linear Interpolation')
df = df['Speed'].interpolate(method='linear')
print(df)

Data with missing Values
   Time  Speed
0     1   10.0
1     2   20.0
2     3    NaN
3     4   40.0
4     5   50.0

Apply the Linear Interpolation
0    10.0
1    20.0
2    30.0
3    40.0
4    50.0
Name: Speed, dtype: float64

In [13]:
'''Polynomial Interpolation'''
import pandas as pd
data = {
    'Time' : [1, 2, 3, 4, 5],
    'Speed': [0, 10, None, 90, 160]
}

df = pd.DataFrame(data)
print('Data with missing Values')
print(df)

print('\nApply the Binomial Interpolation')
df = df['Speed'].interpolate(method='polynomial', order=2)
print(df)

Data with missing Values
   Time  Speed
0     1    0.0
1     2   10.0
2     3    NaN
3     4   90.0
4     5  160.0

Apply the Binomial Interpolation
0      0.0
1     10.0
2     40.0
3     90.0
4    160.0
Name: Speed, dtype: float64