In [17]:
'''
min()
max()
sum()
mean()
count()
std() --> standard deviation
'''

'\nmin()\nmax()\nsum()\nmean()\ncount()\nstd() --> standard deviation\n'

<h1>Grouping Data Pandas</h1>
Make a group of sama data, Like in data you have the Departments column, you can group the pandas frame acc. to Departments.

In [1]:
import pandas as pd

data = {
    'Name' : ['John', 'Dal', 'Bob', 'Harry', 'Rahul', 'Hassan'],
    'Department' : ['HR', 'IT', 'IT', 'Finance', 'HR', 'Finance'],
    'Age' : [24, 45, 37, 27, 23, 24]
}

df = pd.DataFrame(data)
print(df)

# group this data frame by Department.
grouped = df.groupby("Department")['Name'].count()

print(f'\n"Grouped by department and calculate how many department in each column"')
print(grouped)

     Name Department  Age
0    John         HR   24
1     Dal         IT   45
2     Bob         IT   37
3   Harry    Finance   27
4   Rahul         HR   23
5  Hassan    Finance   24

"Grouped by department and calculate how many department in each column"
Department
Finance    2
HR         2
IT         2
Name: Name, dtype: int64

In [2]:
'''Group the employees by Department and calculate the average Salary for each department.'''

'Group the employees by Department and calculate the average Salary for each department.'

In [3]:
import pandas as pd

data = {
    "Employee": [
        "Ali", "Sara", "John", "Ayesha", "David",
        "Hamza", "Emma", "Usman", "Sophia", "Bilal",
        "Ahmed", "Maria"
    ],

    "Department": [
        "IT", "HR", "IT", "Finance", "HR",
        "Finance", "IT", "Marketing", "Marketing", "Finance",
        "HR", "IT"
    ],

    "City": [
        "Lahore", "Karachi", "Lahore", "Islamabad", "Karachi",
        "Lahore", "Islamabad", "Karachi", "Lahore", "Islamabad",
        "Lahore", "Karachi"
    ],

    "Age": [
        25, 30, 28, 35, 27,
        32, 25, 29, 25, 26,
        33, 23
    ],

    "Salary": [
        60000, 55000, 75000, 80000, 65000,
        72000, 58000, 62000, 70000, 68000,
        59000, 67000
    ],

    "Experience": [
        2, 5, 4, 8, 3,
        6, 1, 4, 7, 3,
        6, 2
    ]
}

df = pd.DataFrame(data)
print(df)

print(f'\n Average Salary of each Department.')
grouped = df.groupby('Department')['Salary'].mean()
print(grouped)

   Employee Department       City  Age  Salary  Experience
0       Ali         IT     Lahore   25   60000           2
1      Sara         HR    Karachi   30   55000           5
2      John         IT     Lahore   28   75000           4
3    Ayesha    Finance  Islamabad   35   80000           8
4     David         HR    Karachi   27   65000           3
5     Hamza    Finance     Lahore   32   72000           6
6      Emma         IT  Islamabad   25   58000           1
7     Usman  Marketing    Karachi   29   62000           4
8    Sophia  Marketing     Lahore   25   70000           7
9     Bilal    Finance  Islamabad   26   68000           3
10    Ahmed         HR     Lahore   33   59000           6
11    Maria         IT    Karachi   23   67000           2

 Average Salary of each Department.
Department
Finance      73333.333333
HR           59666.666667
IT           65000.000000
Marketing    66000.000000
Name: Salary, dtype: float64

In [4]:
'''Done ! single column Aggregation'''

'Done ! single column Aggregation'

In [5]:
import pandas as pd

data = {
    "Employee": [
        "Ali", "Ali", "John", "Ayesha", "David",
        "Hamza", "Emma", "Usman", "Sophia", "Bilal",
        "Ahmed", "Maria"
    ],

    "Age": [
        25, 25, 28, 35, 27,
        32, 25, 29, 25, 26,
        33, 23
    ],

    "Salary": [
        60000, 55000, 75000, 80000, 65000,
        72000, 58000, 62000, 70000, 68000,
        59000, 67000
    ]
}

df = pd.DataFrame(data)
print(df)

   Employee  Age  Salary
0       Ali   25   60000
1       Ali   25   55000
2      John   28   75000
3    Ayesha   35   80000
4     David   27   65000
5     Hamza   32   72000
6      Emma   25   58000
7     Usman   29   62000
8    Sophia   25   70000
9     Bilal   26   68000
10    Ahmed   33   59000
11    Maria   23   67000

<h3>Multi Column Grouping and Aggregation</h3>

In [6]:
'''Group by Age , Salary'''
multiCol_group = df.groupby(['Age','Employee'])['Salary'].sum()
multiCol_group

Age  Employee
23   Maria        67000
25   Ali         115000
     Emma         58000
     Sophia       70000
26   Bilal        68000
27   David        65000
28   John         75000
29   Usman        62000
32   Hamza        72000
33   Ahmed        59000
35   Ayesha       80000
Name: Salary, dtype: int64

.agg() function used to apply the aggregation on different columns

In [16]:
'''
First create a new column:

df["Sales"] = df["Quantity"] * df["UnitPrice"]

Then perform multi-column grouping:

Group the data by Category and Region, and calculate:

Total Sales
Average UnitPrice
Total Quantity
Average CustomerRating
'''

'\nFirst create a new column:\n\ndf["Sales"] = df["Quantity"] * df["UnitPrice"]\n\nThen perform multi-column grouping:\n\nGroup the data by Category and Region, and calculate:\n\nTotal Sales\nAverage UnitPrice\nTotal Quantity\nAverage CustomerRating\n'

In [11]:
import pandas as pd

data = {
    "OrderID": [
        1001, 1002, 1003, 1004, 1005,
        1006, 1007, 1008, 1009, 1010,
        1011, 1012, 1013, 1014, 1015,
        1016, 1017, 1018, 1019, 1020
    ],

    "Product": [
        "Laptop", "Smartphone", "Headphones", "Office Chair", "Keyboard",
        "Laptop", "Smartphone", "Monitor", "Mouse", "Headphones",
        "Office Chair", "Laptop", "Monitor", "Smartphone", "Keyboard",
        "Mouse", "Headphones", "Laptop", "Monitor", "Smartphone"
    ],

    "Category": [
        "Electronics", "Electronics", "Accessories", "Furniture", "Accessories",
        "Electronics", "Electronics", "Electronics", "Accessories", "Accessories",
        "Furniture", "Electronics", "Electronics", "Electronics", "Accessories",
        "Accessories", "Accessories", "Electronics", "Electronics", "Electronics"
    ],

    "Region": [
        "North", "South", "North", "East", "West",
        "South", "East", "North", "West", "South",
        "East", "North", "West", "South", "East",
        "North", "West", "South", "East", "North"
    ],

    "PaymentMethod": [
        "Credit Card", "Cash", "Credit Card", "Cash", "Debit Card",
        "Debit Card", "Credit Card", "Cash", "Credit Card", "Cash",
        "Debit Card", "Credit Card", "Cash", "Debit Card", "Credit Card",
        "Cash", "Debit Card", "Credit Card", "Cash", "Debit Card"
    ],

    "Quantity": [
        2, 1, 3, 1, 4,
        1, 2, 2, 5, 2,
        1, 3, 1, 2, 3,
        4, 2, 1, 2, 3
    ],

    "UnitPrice": [
        120000, 85000, 12000, 45000, 5000,
        125000, 80000, 35000, 3000, 15000,
        48000, 115000, 38000, 90000, 5500,
        3500, 14000, 130000, 36000, 82000
    ],

    "Discount": [
        0.05, 0.10, 0.00, 0.05, 0.10,
        0.00, 0.05, 0.10, 0.00, 0.05,
        0.10, 0.05, 0.00, 0.10, 0.05,
        0.00, 0.05, 0.10, 0.00, 0.05
    ],

    "CustomerRating": [
        5, 4, 4, 3, 5,
        4, 5, 4, 3, 5,
        4, 5, 4, 5, 4,
        3, 5, 4, 3, 5
    ]
}

df = pd.DataFrame(data)

print(df)

    OrderID       Product     Category Region PaymentMethod  Quantity  \
0      1001        Laptop  Electronics  North   Credit Card         2
1      1002    Smartphone  Electronics  South          Cash         1
2      1003    Headphones  Accessories  North   Credit Card         3
3      1004  Office Chair    Furniture   East          Cash         1
4      1005      Keyboard  Accessories   West    Debit Card         4
5      1006        Laptop  Electronics  South    Debit Card         1
6      1007    Smartphone  Electronics   East   Credit Card         2
7      1008       Monitor  Electronics  North          Cash         2
8      1009         Mouse  Accessories   West   Credit Card         5
9      1010    Headphones  Accessories  South          Cash         2
10     1011  Office Chair    Furniture   East    Debit Card         1
11     1012        Laptop  Electronics  North   Credit Card         3
12     1013       Monitor  Electronics   West          Cash         1
13     1014    Smartphone  Electronics  South    Debit Card         2
14     1015      Keyboard  Accessories   East   Credit Card         3
15     1016         Mouse  Accessories  North          Cash         4
16     1017    Headphones  Accessories   West    Debit Card         2
17     1018        Laptop  Electronics  South   Credit Card         1
18     1019       Monitor  Electronics   East          Cash         2
19     1020    Smartphone  Electronics  North    Debit Card         3

    UnitPrice  Discount  CustomerRating
0      120000      0.05               5
1       85000      0.10               4
2       12000      0.00               4
3       45000      0.05               3
4        5000      0.10               5
5      125000      0.00               4
6       80000      0.05               5
7       35000      0.10               4
8        3000      0.00               3
9       15000      0.05               5
10      48000      0.10               4
11     115000      0.05               5
12      38000      0.00               4
13      90000      0.10               5
14       5500      0.05               4
15       3500      0.00               3
16      14000      0.05               5
17     130000      0.10               4
18      36000      0.00               3
19      82000      0.05               5

In [12]:
'''find the sales of each product'''
df['Sales'] = df['Quantity'] * df['UnitPrice']
df

,OrderID,Product,Category,Region,PaymentMethod,Quantity,UnitPrice,Discount,CustomerRating,Sales
0,1001,Laptop,Electronics,North,Credit Card,2,120000,0.05,5,240000
1,1002,Smartphone,Electronics,South,Cash,1,85000,0.10,4,85000
2,1003,Headphones,Accessories,North,Credit Card,3,12000,0.00,4,36000
3,1004,Office Chair,Furniture,East,Cash,1,45000,0.05,3,45000
4,1005,Keyboard,Accessories,West,Debit Card,4,5000,0.10,5,20000
5,1006,Laptop,Electronics,South,Debit Card,1,125000,0.00,4,125000
6,1007,Smartphone,Electronics,East,Credit Card,2,80000,0.05,5,160000
7,1008,Monitor,Electronics,North,Cash,2,35000,0.10,4,70000
8,1009,Mouse,Accessories,West,Credit Card,5,3000,0.00,3,15000
9,1010,Headphones,Accessories,South,Cash,2,15000,0.05,5,30000
10,1011,Office Chair,Furniture,East,Debit Card,1,48000,0.10,4,48000
11,1012,Laptop,Electronics,North,Credit Card,3,115000,0.05,5,345000
12,1013,Monitor,Electronics,West,Cash,1,38000,0.00,4,38000
13,1014,Smartphone,Electronics,South,Debit Card,2,90000,0.10,5,180000
14,1015,Keyboard,Accessories,East,Credit Card,3,5500,0.05,4,16500
15,1016,Mouse,Accessories,North,Cash,4,3500,0.00,3,14000
16,1017,Headphones,Accessories,West,Debit Card,2,14000,0.05,5,28000
17,1018,Laptop,Electronics,South,Credit Card,1,130000,0.10,4,130000
18,1019,Monitor,Electronics,East,Cash,2,36000,0.00,3,72000
19,1020,Smartphone,Electronics,North,Debit Card,3,82000,0.05,5,246000

In [15]:
grouped = df.groupby(['Category', 'Region']).agg(
    TotalSales = ('Sales','sum'),
    AverageUnitPrice = ('UnitPrice','mean'),
    TotalQuantity = ('Quantity','sum'),
    AverageCustomeRating=('CustomerRating','mean')
)

grouped

                    TotalSales  AverageUnitPrice  TotalQuantity  \
Category    Region
Accessories East         16500       5500.000000              3
            North        50000       7750.000000              7
            South        30000      15000.000000              2
            West         63000       7333.333333             11
Electronics East        232000      58000.000000              4
            North       901000      88000.000000             10
            South       520000     107500.000000              5
            West         38000      38000.000000              1
Furniture   East         93000      46500.000000              2

                    AverageCustomeRating
Category    Region
Accessories East                4.000000
            North               3.500000
            South               5.000000
            West                4.333333
Electronics East                4.000000
            North               4.750000
            South               4.250000
            West                4.000000
Furniture   East                3.500000

In [11]:
import pandas as pd

data = {
    "OrderID": [
        1001, 1002, 1003, 1004, 1005,
        1006, 1007, 1008, 1009, 1010,
        1011, 1012, 1013, 1014, 1015,
        1016, 1017, 1018, 1019, 1020,
        1021, 1022, 1023, 1024, 1025,
        1026, 1027, 1028, 1029, 1030,
        1031, 1032, 1033, 1034, 1035,
        1036, 1037, 1038, 1039, 1040
    ],

    "CustomerID": [
        "C001", "C002", "C003", "C001", "C004",
        "C005", "C002", "C006", "C001", "C007",
        "C003", "C008", "C005", "C009", "C001",
        "C002", "C010", "C003", "C004", "C006",
        "C001", "C005", "C002", "C007", "C003",
        "C008", "C001", "C009", "C004", "C005",
        "C002", "C006", "C003", "C010", "C001",
        "C007", "C005", "C002", "C008", "C003"
    ],

    "CustomerName": [
        "Ali Khan", "Sara Ahmed", "John Smith", "Ali Khan", "David Lee",
        "Hamza Malik", "Sara Ahmed", "Emma Wilson", "Ali Khan", "Sophia Brown",
        "John Smith", "Usman Tariq", "Hamza Malik", "Ayesha Noor", "Ali Khan",
        "Sara Ahmed", "Michael Chen", "John Smith", "David Lee", "Emma Wilson",
        "Ali Khan", "Hamza Malik", "Sara Ahmed", "Sophia Brown", "John Smith",
        "Usman Tariq", "Ali Khan", "Ayesha Noor", "David Lee", "Hamza Malik",
        "Sara Ahmed", "Emma Wilson", "John Smith", "Michael Chen", "Ali Khan",
        "Sophia Brown", "Hamza Malik", "Sara Ahmed", "Usman Tariq", "John Smith"
    ],

    "Year": [
        2023, 2023, 2023, 2023, 2023,
        2023, 2023, 2023, 2023, 2023,
        2023, 2023, 2023, 2023, 2023,
        2024, 2024, 2024, 2024, 2024,
        2024, 2024, 2024, 2024, 2024,
        2024, 2025, 2025, 2025, 2025,
        2025, 2025, 2025, 2025, 2025,
        2025, 2025, 2025, 2025, 2025
    ],

    "Category": [
        "Electronics", "Clothing", "Electronics", "Home",
        "Furniture", "Electronics", "Clothing", "Beauty",
        "Electronics", "Clothing",
        "Home", "Electronics", "Clothing", "Beauty",
        "Furniture", "Electronics", "Electronics", "Clothing",
        "Furniture", "Beauty", "Electronics", "Clothing",
        "Home", "Electronics", "Clothing", "Beauty",
        "Electronics", "Beauty", "Furniture", "Clothing",
        "Electronics", "Beauty", "Electronics", "Clothing",
        "Home", "Electronics", "Clothing", "Electronics",
        "Beauty", "Home"
    ],

    "Quantity": [
        2, 1, 1, 3, 1,
        2, 2, 1, 1, 3,
        2, 1, 2, 2, 1,
        2, 3, 2, 1, 2,
        3, 2, 3, 1, 2,
        2, 2, 3, 2, 4,
        3, 2, 4, 2, 3,
        2, 3, 2, 3, 4
    ],

    "Amount": [
        45000, 8000, 55000, 18000, 70000,
        40000, 12000, 9000, 60000, 15000,
        22000, 35000, 14000, 11000, 65000,
        48000, 75000, 20000, 85000, 13000,
        72000, 25000, 18000, 12000, 30000,
        16000, 85000, 18000, 90000, 28000,
        22000, 15000, 55000, 80000, 95000,
        17000, 35000, 42000, 19000, 45000
    ],

    "PaymentMethod": [
        "Card", "Cash", "Card", "Online", "Card",
        "Online", "Cash", "Card", "Card", "Cash",
        "Online", "Card", "Cash", "Online", "Card",
        "Card", "Online", "Cash", "Card", "Online",
        "Card", "Cash", "Online", "Card", "Cash",
        "Online", "Card", "Cash", "Card", "Online",
        "Card", "Cash", "Online", "Card", "Card",
        "Cash", "Online", "Card", "Cash", "Online"
    ]
}

df = pd.DataFrame(data)

print(df)

    OrderID CustomerID  CustomerName  Year     Category  Quantity  Amount  \
0      1001       C001      Ali Khan  2023  Electronics         2   45000
1      1002       C002    Sara Ahmed  2023     Clothing         1    8000
2      1003       C003    John Smith  2023  Electronics         1   55000
3      1004       C001      Ali Khan  2023         Home         3   18000
4      1005       C004     David Lee  2023    Furniture         1   70000
5      1006       C005   Hamza Malik  2023  Electronics         2   40000
6      1007       C002    Sara Ahmed  2023     Clothing         2   12000
7      1008       C006   Emma Wilson  2023       Beauty         1    9000
8      1009       C001      Ali Khan  2023  Electronics         1   60000
9      1010       C007  Sophia Brown  2023     Clothing         3   15000
10     1011       C003    John Smith  2023         Home         2   22000
11     1012       C008   Usman Tariq  2023  Electronics         1   35000
12     1013       C005   Hamza Malik  2023     Clothing         2   14000
13     1014       C009   Ayesha Noor  2023       Beauty         2   11000
14     1015       C001      Ali Khan  2023    Furniture         1   65000
15     1016       C002    Sara Ahmed  2024  Electronics         2   48000
16     1017       C010  Michael Chen  2024  Electronics         3   75000
17     1018       C003    John Smith  2024     Clothing         2   20000
18     1019       C004     David Lee  2024    Furniture         1   85000
19     1020       C006   Emma Wilson  2024       Beauty         2   13000
20     1021       C001      Ali Khan  2024  Electronics         3   72000
21     1022       C005   Hamza Malik  2024     Clothing         2   25000
22     1023       C002    Sara Ahmed  2024         Home         3   18000
23     1024       C007  Sophia Brown  2024  Electronics         1   12000
24     1025       C003    John Smith  2024     Clothing         2   30000
25     1026       C008   Usman Tariq  2024       Beauty         2   16000
26     1027       C001      Ali Khan  2025  Electronics         2   85000
27     1028       C009   Ayesha Noor  2025       Beauty         3   18000
28     1029       C004     David Lee  2025    Furniture         2   90000
29     1030       C005   Hamza Malik  2025     Clothing         4   28000
30     1031       C002    Sara Ahmed  2025  Electronics         3   22000
31     1032       C006   Emma Wilson  2025       Beauty         2   15000
32     1033       C003    John Smith  2025  Electronics         4   55000
33     1034       C010  Michael Chen  2025     Clothing         2   80000
34     1035       C001      Ali Khan  2025         Home         3   95000
35     1036       C007  Sophia Brown  2025  Electronics         2   17000
36     1037       C005   Hamza Malik  2025     Clothing         3   35000
37     1038       C002    Sara Ahmed  2025  Electronics         2   42000
38     1039       C008   Usman Tariq  2025       Beauty         3   19000
39     1040       C003    John Smith  2025         Home         4   45000

   PaymentMethod
0           Card
1           Cash
2           Card
3         Online
4           Card
5         Online
6           Cash
7           Card
8           Card
9           Cash
10        Online
11          Card
12          Cash
13        Online
14          Card
15          Card
16        Online
17          Cash
18          Card
19        Online
20          Card
21          Cash
22        Online
23          Card
24          Cash
25        Online
26          Card
27          Cash
28          Card
29        Online
30          Card
31          Cash
32        Online
33          Card
34          Card
35          Cash
36        Online
37          Card
38          Cash
39        Online

In [ ]:
'''
⭐ Loyal customer identification(regular and frequent)

criteria (active in all 3 years and no. of order>=4)

Find customers who:

purchased in 2023
AND purchased in 2024
AND purchased in 2025
'''

In [12]:
df = df.groupby(['CustomerID','CustomerName']).agg(
    TotalOrders=('OrderID','count'),
    AmountSpend=('Amount','sum'),
    YearsActive=('Year','nunique')
)
df

                         TotalOrders  AmountSpend  YearsActive
CustomerID CustomerName
C001       Ali Khan                7       440000            3
C002       Sara Ahmed              6       150000            3
C003       John Smith              6       227000            3
C004       David Lee               3       245000            3
C005       Hamza Malik             5       142000            3
C006       Emma Wilson             3        37000            3
C007       Sophia Brown            3        44000            3
C008       Usman Tariq             3        70000            3
C009       Ayesha Noor             2        29000            2
C010       Michael Chen            2       155000            2

In [15]:
loyalCustomers = df[(df['TotalOrders'] >= 4) & (df['YearsActive'] == 3)]
print('Loyal Customer of Company')
print(loyalCustomers)

Loyal Customer of Company
                         TotalOrders  AmountSpend  YearsActive
CustomerID CustomerName
C001       Ali Khan                7       440000            3
C002       Sara Ahmed              6       150000            3
C003       John Smith              6       227000            3
C005       Hamza Malik             5       142000            3

In [16]:
import pandas as pd

data = {
    "Employee": [
        "Ali", "Sara", "John", "Ayesha", "David",
        "Hamza", "Emma", "Usman", "Sophia", "Bilal",
        "Ahmed", "Maria"
    ],

    "Department": [
        "IT", "HR", "IT", "Finance", "HR",
        "Finance", "IT", "Marketing", "Marketing", "Finance",
        "HR", "IT"
    ],

    "City": [
        "Lahore", "Karachi", "Lahore", "Islamabad", "Karachi",
        "Lahore", "Islamabad", "Karachi", "Lahore", "Islamabad",
        "Lahore", "Karachi"
    ],

    "Age": [
        25, 30, 28, 35, 27,
        32, 25, 29, 25, 26,
        33, 23
    ],

    "Salary": [
        60000, 55000, 75000, 80000, 65000,
        72000, 58000, 62000, 70000, 68000,
        59000, 67000
    ],

    "Experience": [
        2, 5, 4, 8, 3,
        6, 1, 4, 7, 3,
        6, 2
    ]
}

df = pd.DataFrame(data)
print(df)

   Employee Department       City  Age  Salary  Experience
0       Ali         IT     Lahore   25   60000           2
1      Sara         HR    Karachi   30   55000           5
2      John         IT     Lahore   28   75000           4
3    Ayesha    Finance  Islamabad   35   80000           8
4     David         HR    Karachi   27   65000           3
5     Hamza    Finance     Lahore   32   72000           6
6      Emma         IT  Islamabad   25   58000           1
7     Usman  Marketing    Karachi   29   62000           4
8    Sophia  Marketing     Lahore   25   70000           7
9     Bilal    Finance  Islamabad   26   68000           3
10    Ahmed         HR     Lahore   33   59000           6
11    Maria         IT    Karachi   23   67000           2

In [18]:
df.sort_index(ascending=True)
df

   Employee Department       City  Age  Salary  Experience
0       Ali         IT     Lahore   25   60000           2
1      Sara         HR    Karachi   30   55000           5
2      John         IT     Lahore   28   75000           4
3    Ayesha    Finance  Islamabad   35   80000           8
4     David         HR    Karachi   27   65000           3
5     Hamza    Finance     Lahore   32   72000           6
6      Emma         IT  Islamabad   25   58000           1
7     Usman  Marketing    Karachi   29   62000           4
8    Sophia  Marketing     Lahore   25   70000           7
9     Bilal    Finance  Islamabad   26   68000           3
10    Ahmed         HR     Lahore   33   59000           6
11    Maria         IT    Karachi   23   67000           2