In [31]:
'''concatenate the dataframe, row wise and column wise'''
'''pd.concat([df1, df2], axis=1, ignore_index=True)'''

'''
- [df1, df2] -> data to concatenate between different dataframe
- axis=0 -> rowwise (vertically) and axis=1 (horizontally)
- ignore_index=True  -> to reset the index after concatenation
'''

'\n- [df1, df2] -> data to concatenate between different dataframe\n- axis=0 -> rowwise (vertically) and axis=1 (horizontally)\n- ignore_index=True  -> to reset the index after concatenation\n'

In [32]:
import pandas as pd

In [33]:
df_employees1 = pd.DataFrame({
    'emp_id': [101, 102, 103, 104],
    'name': ['Alice', 'Bob', 'Charlie', 'David'],
    'dept': ['HR', 'IT', 'IT', 'Finance']
})

df_employees2 = pd.DataFrame({
    'emp_id': [105, 106, 107, 108],
    'name': ['Eva', 'Frank', 'Grace', 'Henry'],
    'dept': ['Finance', 'Marketing', 'HR', 'IT']
})

all_emp=pd.concat([df_employees1, df_employees2], axis=0, ignore_index=True)
all_emp

   emp_id     name       dept
0     101    Alice         HR
1     102      Bob         IT
2     103  Charlie         IT
3     104    David    Finance
4     105      Eva    Finance
5     106    Frank  Marketing
6     107    Grace         HR
7     108    Henry         IT

<h1>Task Merge then Concatenate the two df<h1>

In [34]:
import pandas as pd

customer_data = {
    "CustomerID": [
        "C001", "C002", "C003", "C004", "C005",
        "C006", "C007", "C008", "C009", "C010"
    ],

    "CustomerName": [
        "Ali Khan", "Sara Ahmed", "John Smith", "Ayesha Noor",
        "David Lee", "Hamza Malik", "Emma Wilson",
        "Usman Tariq", "Sophia Brown", "Michael Chen"
    ],

    "Age": [
        25, 31, 28, 35, 42,
        24, 29, 38, 33, 45
    ],

    "Gender": [
        "Male", "Female", "Male", "Female", "Male",
        "Male", "Female", "Male", "Female", "Male"
    ],

    "City": [
        "Lahore", "Karachi", "Islamabad", "Lahore", "Multan",
        "Karachi", "Islamabad", "Lahore", "Karachi", "Multan"
    ],

    "Membership": [
        "Gold", "Silver", "Gold", "Platinum", "Silver",
        "Gold", "Silver", "Platinum", "Gold", "Silver"
    ]
}

CustomerProfile = pd.DataFrame(customer_data)

print(CustomerProfile)

  CustomerID  CustomerName  Age  Gender       City Membership
0       C001      Ali Khan   25    Male     Lahore       Gold
1       C002    Sara Ahmed   31  Female    Karachi     Silver
2       C003    John Smith   28    Male  Islamabad       Gold
3       C004   Ayesha Noor   35  Female     Lahore   Platinum
4       C005     David Lee   42    Male     Multan     Silver
5       C006   Hamza Malik   24    Male    Karachi       Gold
6       C007   Emma Wilson   29  Female  Islamabad     Silver
7       C008   Usman Tariq   38    Male     Lahore   Platinum
8       C009  Sophia Brown   33  Female    Karachi       Gold
9       C010  Michael Chen   45    Male     Multan     Silver

In [35]:
transaction_data = {
    "TransactionID": [
        "T001", "T002", "T003", "T004", "T005",
        "T006", "T007", "T008", "T009", "T010",
        "T011", "T012", "T013", "T014", "T015",
        "T016", "T017", "T018", "T019", "T020"
    ],

    "CustomerID": [
        "C001", "C002", "C001", "C003", "C004",
        "C002", "C005", "C006", "C001", "C007",
        "C003", "C008", "C005", "C009", "C002",
        "C004", "C006", "C010", "C001", "C003"
    ],

    "Year": [
        2023, 2023, 2024, 2023, 2023,
        2024, 2023, 2024, 2025, 2024,
        2024, 2023, 2025, 2024, 2025,
        2025, 2025, 2023, 2025, 2025
    ],

    "Product": [
        "Laptop", "Shoes", "Smartphone", "Headphones", "Office Chair",
        "Jacket", "Laptop", "Monitor", "Tablet", "Shoes",
        "Keyboard", "Smartphone", "Headphones", "Camera", "Jacket",
        "Office Chair", "Mouse", "Laptop", "Smartphone", "Monitor"
    ],

    "Category": [
        "Electronics", "Fashion", "Electronics", "Electronics", "Furniture",
        "Fashion", "Electronics", "Electronics", "Electronics", "Fashion",
        "Electronics", "Electronics", "Electronics", "Electronics", "Fashion",
        "Furniture", "Electronics", "Electronics", "Electronics", "Electronics"
    ],

    "Quantity": [
        1, 2, 1, 2, 1,
        2, 1, 2, 1, 3,
        2, 1, 2, 1, 2,
        1, 3, 1, 2, 1
    ],

    "Amount": [
        120000, 15000, 85000, 18000, 45000,
        22000, 115000, 70000, 55000, 18000,
        8000, 90000, 16000, 75000, 25000,
        50000, 9000, 125000, 95000, 40000
    ],

    "PaymentMethod": [
        "Card", "Cash", "Online", "Card", "Card",
        "Cash", "Online", "Card", "Online", "Cash",
        "Card", "Online", "Card", "Cash", "Online",
        "Card", "Cash", "Card", "Online", "Card"
    ]
}

TransactionHistory = pd.DataFrame(transaction_data)

print(TransactionHistory)

   TransactionID CustomerID  Year       Product     Category  Quantity  \
0           T001       C001  2023        Laptop  Electronics         1
1           T002       C002  2023         Shoes      Fashion         2
2           T003       C001  2024    Smartphone  Electronics         1
3           T004       C003  2023    Headphones  Electronics         2
4           T005       C004  2023  Office Chair    Furniture         1
5           T006       C002  2024        Jacket      Fashion         2
6           T007       C005  2023        Laptop  Electronics         1
7           T008       C006  2024       Monitor  Electronics         2
8           T009       C001  2025        Tablet  Electronics         1
9           T010       C007  2024         Shoes      Fashion         3
10          T011       C003  2024      Keyboard  Electronics         2
11          T012       C008  2023    Smartphone  Electronics         1
12          T013       C005  2025    Headphones  Electronics         2
13          T014       C009  2024        Camera  Electronics         1
14          T015       C002  2025        Jacket      Fashion         2
15          T016       C004  2025  Office Chair    Furniture         1
16          T017       C006  2025         Mouse  Electronics         3
17          T018       C010  2023        Laptop  Electronics         1
18          T019       C001  2025    Smartphone  Electronics         2
19          T020       C003  2025       Monitor  Electronics         1

    Amount PaymentMethod
0   120000          Card
1    15000          Cash
2    85000        Online
3    18000          Card
4    45000          Card
5    22000          Cash
6   115000        Online
7    70000          Card
8    55000        Online
9    18000          Cash
10    8000          Card
11   90000        Online
12   16000          Card
13   75000          Cash
14   25000        Online
15   50000          Card
16    9000          Cash
17  125000          Card
18   95000        Online
19   40000          Card

In [36]:
customer1=pd.merge(CustomerProfile, TransactionHistory, on='CustomerID', how='inner')
customer1

,CustomerID,CustomerName,Age,Gender,City,Membership,TransactionID,Year,Product,Category,Quantity,Amount,PaymentMethod
0,C001,Ali Khan,25,Male,Lahore,Gold,T001,2023,Laptop,Electronics,1,120000,Card
1,C001,Ali Khan,25,Male,Lahore,Gold,T003,2024,Smartphone,Electronics,1,85000,Online
2,C001,Ali Khan,25,Male,Lahore,Gold,T009,2025,Tablet,Electronics,1,55000,Online
3,C001,Ali Khan,25,Male,Lahore,Gold,T019,2025,Smartphone,Electronics,2,95000,Online
4,C002,Sara Ahmed,31,Female,Karachi,Silver,T002,2023,Shoes,Fashion,2,15000,Cash
5,C002,Sara Ahmed,31,Female,Karachi,Silver,T006,2024,Jacket,Fashion,2,22000,Cash
6,C002,Sara Ahmed,31,Female,Karachi,Silver,T015,2025,Jacket,Fashion,2,25000,Online
7,C003,John Smith,28,Male,Islamabad,Gold,T004,2023,Headphones,Electronics,2,18000,Card
8,C003,John Smith,28,Male,Islamabad,Gold,T011,2024,Keyboard,Electronics,2,8000,Card
9,C003,John Smith,28,Male,Islamabad,Gold,T020,2025,Monitor,Electronics,1,40000,Card
10,C004,Ayesha Noor,35,Female,Lahore,Platinum,T005,2023,Office Chair,Furniture,1,45000,Card
11,C004,Ayesha Noor,35,Female,Lahore,Platinum,T016,2025,Office Chair,Furniture,1,50000,Card
12,C005,David Lee,42,Male,Multan,Silver,T007,2023,Laptop,Electronics,1,115000,Online
13,C005,David Lee,42,Male,Multan,Silver,T013,2025,Headphones,Electronics,2,16000,Card
14,C006,Hamza Malik,24,Male,Karachi,Gold,T008,2024,Monitor,Electronics,2,70000,Card
15,C006,Hamza Malik,24,Male,Karachi,Gold,T017,2025,Mouse,Electronics,3,9000,Cash
16,C007,Emma Wilson,29,Female,Islamabad,Silver,T010,2024,Shoes,Fashion,3,18000,Cash
17,C008,Usman Tariq,38,Male,Lahore,Platinum,T012,2023,Smartphone,Electronics,1,90000,Online
18,C009,Sophia Brown,33,Female,Karachi,Gold,T014,2024,Camera,Electronics,1,75000,Cash
19,C010,Michael Chen,45,Male,Multan,Silver,T018,2023,Laptop,Electronics,1,125000,Card

In [38]:
'''Find the Total Spending of every customer'''

'Find the Total Spending of every customer'

In [39]:
df = customer1.groupby(['CustomerID','CustomerName']).agg(
    TotalSpending=('Amount','sum')
)
df

                         TotalSpending
CustomerID CustomerName
C001       Ali Khan             355000
C002       Sara Ahmed            62000
C003       John Smith            66000
C004       Ayesha Noor           95000
C005       David Lee            131000
C006       Hamza Malik           79000
C007       Emma Wilson           18000
C008       Usman Tariq           90000
C009       Sophia Brown          75000
C010       Michael Chen         125000

In [ ]:
'''now concatenate the data cusomter1 (dataframe) + customer2(dataframe)'''